// <auto-generated />
using System;
using BPBank.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BPBank.Data.Migrations
{
    [DbContext(typeof(BPBankContext))]
    [Migration("20210516204614_InitBPBankDB")]
    partial class InitBPBankDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BPBank.Domain.Entities.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AccNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("BaseCcyId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BaseCcyId");

                    b.HasIndex("UserId");

                    b.ToTable("Accounts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccNumber = "123456",
                            Balance = 25000m,
                            BaseCcyId = 1,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            AccNumber = "764321",
                            Balance = 47000m,
                            BaseCcyId = 2,
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            AccNumber = "827419",
                            Balance = 8000m,
                            BaseCcyId = 3,
                            UserId = 2
                        },
                        new
                        {
                            Id = 4,
                            AccNumber = "243970",
                            Balance = 4000m,
                            BaseCcyId = 1,
                            UserId = 1
                        },
                        new
                        {
                            Id = 5,
                            AccNumber = "100321",
                            Balance = 500m,
                            BaseCcyId = 1,
                            UserId = 1
                        });
                });

            modelBuilder.Entity("BPBank.Domain.Entities.Currency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExternalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ISOCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Currencys");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "British Pounds",
                            ISOCode = "GBP"
                        },
                        new
                        {
                            Id = 2,
                            Description = "United States Dollars",
                            ISOCode = "USD"
                        },
                        new
                        {
                            Id = 3,
                            Description = "EU Euros",
                            ISOCode = "EUR"
                        });
                });

            modelBuilder.Entity("BPBank.Domain.Entities.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AccountId")
                        .HasColumnType("int");

                    b.Property<int>("FromAccountId")
                        .HasColumnType("int");

                    b.Property<decimal>("FromAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("FromCcyId")
                        .HasColumnType("int");

                    b.Property<int>("Operation")
                        .HasColumnType("int");

                    b.Property<int>("ToAccountId")
                        .HasColumnType("int");

                    b.Property<decimal>("ToAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("ToCcyId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("BPBank.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoginName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Fred",
                            LoginName = "fred",
                            Surname = "Flintstone"
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Barney",
                            LoginName = "barney",
                            Surname = "Rubble"
                        });
                });

            modelBuilder.Entity("BPBank.Domain.Entities.Account", b =>
                {
                    b.HasOne("BPBank.Domain.Entities.Currency", "BaseCcy")
                        .WithMany()
                        .HasForeignKey("BaseCcyId");

                    b.HasOne("BPBank.Domain.Entities.User", null)
                        .WithMany("Accounts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BaseCcy");
                });

            modelBuilder.Entity("BPBank.Domain.Entities.Transaction", b =>
                {
                    b.HasOne("BPBank.Domain.Entities.Account", null)
                        .WithMany("Transactions")
                        .HasForeignKey("AccountId");
                });

            modelBuilder.Entity("BPBank.Domain.Entities.Account", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("BPBank.Domain.Entities.User", b =>
                {
                    b.Navigation("Accounts");
                });
#pragma warning restore 612, 618
        }
    }
}
